title: Justin Whitlock
logo: Face_Profile_Picture.jpg
description: "Justin Whitlock | IT Management & Data Analytics Enthusiast

I am a dedicated Information Technology Management student at Florida State College in Jacksonville, targeting a Bachelor's degree by December 2024. With a strong foundation in Excel, Power BI, Microsoft SQL, and Python, my analytical mindset drives my passion for leveraging technology to solve complex problems and innovate. As an IT Lab Assistant and former S.T.E.M. Club President, I excel in project management, technical coordination, and leadership, aiming to make a significant impact in technology and data analytics. My background, including a 3.4 GPA and experiences ranging from IT Analyst Intern to Robotics Inspector, reflects a commitment to continuous learning and excellence."
show_downloads: true
theme: jekyll-theme-minimal
